"""Initial migration for the Identity module.

Hand-written rather than autogenerated: this sandbox has no PyPI/network
access to install Django and run `makemigrations` against a real database.
Every field here was cross-checked field-by-field against
infrastructure/models.py (see this phase's verification step) rather than
trusted from memory. Run `python manage.py makemigrations --check` after
pulling this into an environment with dependencies installed, as a final
confirmation that this migration matches the models exactly.
"""
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

import shared_kernel.infrastructure.uuid7


def _base_fields() -> list[tuple[str, object]]:
    """The four fields every BaseModel-derived model carries
    (shared_kernel/infrastructure/base_models.py) — factored out so each
    CreateModel below can't drift from what BaseModel actually defines.
    """
    return [
        (
            "id",
            models.UUIDField(
                default=shared_kernel.infrastructure.uuid7.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("created_by", models.UUIDField(blank=True, null=True)),
        ("updated_by", models.UUIDField(blank=True, null=True)),
    ]


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRecord",
            fields=[
                *_base_fields(),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("employee_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_account", models.BooleanField(default=False)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("password_changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "identity_users"},
        ),
        migrations.CreateModel(
            name="RoleRecord",
            fields=[
                *_base_fields(),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_system_role", models.BooleanField(default=False)),
            ],
            options={"db_table": "identity_roles"},
        ),
        migrations.CreateModel(
            name="PermissionRecord",
            fields=[
                *_base_fields(),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("module", models.CharField(default="identity", max_length=50)),
            ],
            options={"db_table": "identity_permissions"},
        ),
        migrations.CreateModel(
            name="UserRoleRecord",
            fields=[
                *_base_fields(),
                ("assigned_by", models.UUIDField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="identity.rolerecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to="identity.userrecord",
                    ),
                ),
            ],
            options={"db_table": "identity_user_roles"},
        ),
        migrations.CreateModel(
            name="RolePermissionRecord",
            fields=[
                *_base_fields(),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to="identity.permissionrecord",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_links",
                        to="identity.rolerecord",
                    ),
                ),
            ],
            options={"db_table": "identity_role_permissions"},
        ),
        migrations.CreateModel(
            name="PasswordResetTokenRecord",
            fields=[
                *_base_fields(),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="identity.userrecord",
                    ),
                ),
            ],
            options={"db_table": "identity_password_reset_tokens"},
        ),
        migrations.AddField(
            model_name="rolerecord",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="identity.RolePermissionRecord",
                to="identity.permissionrecord",
            ),
        ),
        migrations.AddField(
            model_name="userrecord",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="identity.UserRoleRecord",
                to="identity.rolerecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrolerecord",
            constraint=models.UniqueConstraint(fields=("user", "role"), name="unique_user_role"),
        ),
        migrations.AddConstraint(
            model_name="rolepermissionrecord",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="userrecord",
            index=models.Index(fields=["is_active"], name="identity_users_active_idx"),
        ),
    ]
